# Configurazione mappa "Hotel - Piano 3"

Descrizione completa della mappa: stanze (aree), muri, oggetti e personaggi. Coordinate come (riga, colonna) a partire da 1.

Griglia 6×6. Regole: una sola persona per riga e per colonna; "accanto" = celle adiacenti nella stessa area (i muri bloccano); la vittima è sola con l'assassino (nella sua area c'è esattamente un sospetto).

## Stanze / aree

- **A = Stanza 312** — celle occupabili: (1,1), (1,2), (2,2), (3,1)
- **B = Corridoio** — celle occupabili: (1,3), (1,4), (2,4), (3,3), (3,4), (4,3), (4,4), (5,3), (5,4), (6,3), (6,4)
- **C = Stanza 314** — celle occupabili: (1,5), (1,6), (2,5), (2,6), (3,5), (3,6)
- **D = Stanza 313** — celle occupabili: (4,2), (5,1), (5,2), (6,2)
- **E = Stanza 315** — celle occupabili: (4,5), (4,6), (5,5), (5,6), (6,5), (6,6)

**Griglia di aree e muri** — `┃`/`━` = muro tra due celle; `#` = cella bloccata:
```
     1   2   3   4   5   6  
1 |  A   A ┃ B   B ┃ C   C 
  |                        
2 |  a   A ┃ b   B ┃ C   C 
  |                        
3 |  A   a ┃ B   B ┃ C   C 
  | ━━━ ━━━         ━━━ ━━━
4 |  d   D ┃ B   B ┃ E   E 
  |                        
5 |  D   D ┃ B   B ┃ E   E 
  |                        
6 |  d   D ┃ B   B ┃ E   E 
```

## Muri (coppie di celle separate)

- stessa riga: (1,2)|(1,3), (1,4)|(1,5), (2,2)|(2,3), (2,4)|(2,5), (3,2)|(3,3), (3,4)|(3,5), (4,2)|(4,3), (4,4)|(4,5), (5,2)|(5,3), (5,4)|(5,5), (6,2)|(6,3), (6,4)|(6,5)
- stessa colonna: (3,1)|(4,1), (3,2)|(4,2), (3,5)|(4,5), (3,6)|(4,6)

## Oggetti (elementi)

Minuscolo = calpestabile, MAIUSCOLO = ostacolo, `..` = vuota, `##` = bloccata:
```
     1   2   3   4   5   6  
1 | .. .. ta2 .. .. .. 
2 | TV .. VDP .. .. .. 
3 | se TA .. .. .. le 
4 | LA le .. ta2 .. .. 
5 | .. .. .. .. le .. 
6 | VDP .. se .. .. .. 
```

**Legenda oggetti:**
- `ta2` = Tappeto (calpestabile)
- `TV` = TV (ostacolo)
- `VDP` = Vaso di piante (ostacolo)
- `se` = Sedia (calpestabile)
- `TA` = Tavolo (ostacolo)
- `le` = Letto (calpestabile)
- `LA` = Lampada (ostacolo)

**Celle bloccate:** nessuna

**Oggetti per cella:** (1,3) Tappeto (calpestabile); (2,1) TV (ostacolo); (2,3) Vaso di piante (ostacolo); (3,1) Sedia (calpestabile); (3,2) Tavolo (ostacolo); (3,6) Letto (calpestabile); (4,1) Lampada (ostacolo); (4,2) Letto (calpestabile); (4,4) Tappeto (calpestabile); (5,5) Letto (calpestabile); (6,1) Vaso di piante (ostacolo); (6,3) Sedia (calpestabile).

## Personaggi

- A = Arturo: (2,2) — **assassino**
- B = Beatrice: (3,3)
- C = Chiara: (4,6)
- D = Diego: (5,5)
- E = Elio: (6,4)
- V = Zita (vittima): (1,1)

**Assassino: Arturo** — unico sospetto nell'area della vittima.

<!-- MURDOKU_STATE_B64: eyJ2ZXJzaW9uIjoxLCJ0aXRsZSI6IkhvdGVsIC0gUGlhbm8gMyIsInNpemUiOjYsImNlbGxzIjpbeyJyb3ciOjAsImNvbCI6MCwid2Fsa2FibGUiOnRydWUsIm9iamVjdCI6bnVsbH0seyJyb3ciOjAsImNvbCI6MSwid2Fsa2FibGUiOnRydWUsIm9iamVjdCI6bnVsbH0seyJyb3ciOjAsImNvbCI6Miwid2Fsa2FibGUiOnRydWUsIm9iamVjdCI6InRhcHBldG8ifSx7InJvdyI6MCwiY29sIjozLCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjpudWxsfSx7InJvdyI6MCwiY29sIjo0LCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjpudWxsfSx7InJvdyI6MCwiY29sIjo1LCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjpudWxsfSx7InJvdyI6MSwiY29sIjowLCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjoidHYifSx7InJvdyI6MSwiY29sIjoxLCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjpudWxsfSx7InJvdyI6MSwiY29sIjoyLCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjoidmFzb19kaV9waWFudGUifSx7InJvdyI6MSwiY29sIjozLCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjpudWxsfSx7InJvdyI6MSwiY29sIjo0LCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjpudWxsfSx7InJvdyI6MSwiY29sIjo1LCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjpudWxsfSx7InJvdyI6MiwiY29sIjowLCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0Ijoic2VkaWEifSx7InJvdyI6MiwiY29sIjoxLCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjoidGF2b2xvIn0seyJyb3ciOjIsImNvbCI6Miwid2Fsa2FibGUiOnRydWUsIm9iamVjdCI6bnVsbH0seyJyb3ciOjIsImNvbCI6Mywid2Fsa2FibGUiOnRydWUsIm9iamVjdCI6bnVsbH0seyJyb3ciOjIsImNvbCI6NCwid2Fsa2FibGUiOnRydWUsIm9iamVjdCI6bnVsbH0seyJyb3ciOjIsImNvbCI6NSwid2Fsa2FibGUiOnRydWUsIm9iamVjdCI6ImxldHRvIn0seyJyb3ciOjMsImNvbCI6MCwid2Fsa2FibGUiOnRydWUsIm9iamVjdCI6ImxhbXBhZGEifSx7InJvdyI6MywiY29sIjoxLCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjoibGV0dG8ifSx7InJvdyI6MywiY29sIjoyLCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjpudWxsfSx7InJvdyI6MywiY29sIjozLCJ3YWxrYWJsZSI6dHJ1ZSwib2JqZWN0IjoidGFwcGV0byJ9LHsicm93IjozLCJjb2wiOjQsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOm51bGx9LHsicm93IjozLCJjb2wiOjUsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOm51bGx9LHsicm93Ijo0LCJjb2wiOjAsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOm51bGx9LHsicm93Ijo0LCJjb2wiOjEsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOm51bGx9LHsicm93Ijo0LCJjb2wiOjIsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOm51bGx9LHsicm93Ijo0LCJjb2wiOjMsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOm51bGx9LHsicm93Ijo0LCJjb2wiOjQsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOiJsZXR0byJ9LHsicm93Ijo0LCJjb2wiOjUsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOm51bGx9LHsicm93Ijo1LCJjb2wiOjAsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOiJ2YXNvX2RpX3BpYW50ZSJ9LHsicm93Ijo1LCJjb2wiOjEsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOm51bGx9LHsicm93Ijo1LCJjb2wiOjIsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOiJzZWRpYSJ9LHsicm93Ijo1LCJjb2wiOjMsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOm51bGx9LHsicm93Ijo1LCJjb2wiOjQsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOm51bGx9LHsicm93Ijo1LCJjb2wiOjUsIndhbGthYmxlIjp0cnVlLCJvYmplY3QiOm51bGx9XSwid2FsbHMiOlsiMCwxfDAsMiIsIjEsMXwxLDIiLCIyLDF8MiwyIiwiMywxfDMsMiIsIjQsMXw0LDIiLCI1LDF8NSwyIiwiMCwzfDAsNCIsIjEsM3wxLDQiLCIyLDN8Miw0IiwiMywzfDMsNCIsIjQsM3w0LDQiLCI1LDN8NSw0IiwiMiwwfDMsMCIsIjIsMXwzLDEiLCIyLDR8Myw0IiwiMiw1fDMsNSJdLCJ3aW5kb3dzIjpbXSwiZG9vcnMiOltdLCJhcmVhTmFtZXMiOnsiMCI6IlN0YW56YSAzMTIiLCIxIjoiQ29ycmlkb2lvIiwiMiI6IlN0YW56YSAzMTQiLCIzIjoiU3RhbnphIDMxMyIsIjQiOiJTdGFuemEgMzE1In0sImFyZWFGbG9vcnMiOnt9LCJlbnRpdGllcyI6W3siaWQiOiJzMCIsImtpbmQiOiJzdXNwZWN0IiwiaW5pdGlhbCI6IkEiLCJuYW1lIjoiQXJ0dXJvIiwicm93IjoxLCJjb2wiOjEsImlzTXVyZGVyZXIiOnRydWUsImdlbmRlciI6Ik0iLCJoYXNIYXQiOmZhbHNlLCJoYXNHbGFzc2VzIjpmYWxzZX0seyJpZCI6InMxIiwia2luZCI6InN1c3BlY3QiLCJpbml0aWFsIjoiQiIsIm5hbWUiOiJCZWF0cmljZSIsInJvdyI6MiwiY29sIjoyLCJpc011cmRlcmVyIjpmYWxzZSwiZ2VuZGVyIjoiRiIsImhhc0hhdCI6dHJ1ZSwiaGFzR2xhc3NlcyI6dHJ1ZX0seyJpZCI6InMyIiwia2luZCI6InN1c3BlY3QiLCJpbml0aWFsIjoiQyIsIm5hbWUiOiJDaGlhcmEiLCJyb3ciOjMsImNvbCI6NSwiaXNNdXJkZXJlciI6ZmFsc2UsImdlbmRlciI6IkYiLCJoYXNIYXQiOmZhbHNlLCJoYXNHbGFzc2VzIjp0cnVlfSx7ImlkIjoiczMiLCJraW5kIjoic3VzcGVjdCIsImluaXRpYWwiOiJEIiwibmFtZSI6IkRpZWdvIiwicm93Ijo0LCJjb2wiOjQsImlzTXVyZGVyZXIiOmZhbHNlLCJnZW5kZXIiOiJNIiwiaGFzSGF0Ijp0cnVlLCJoYXNHbGFzc2VzIjpmYWxzZX0seyJpZCI6InM0Iiwia2luZCI6InN1c3BlY3QiLCJpbml0aWFsIjoiRSIsIm5hbWUiOiJFbGlvIiwicm93Ijo1LCJjb2wiOjMsImlzTXVyZGVyZXIiOmZhbHNlLCJnZW5kZXIiOiJNIiwiaGFzSGF0IjpmYWxzZSwiaGFzR2xhc3NlcyI6dHJ1ZX0seyJpZCI6InZpY3RpbSIsImtpbmQiOiJ2aWN0aW0iLCJpbml0aWFsIjoiViIsIm5hbWUiOiJaaXRhIiwicm93IjowLCJjb2wiOjAsImlzTXVyZGVyZXIiOmZhbHNlLCJnZW5kZXIiOiJGIiwiaGFzSGF0IjpmYWxzZSwiaGFzR2xhc3NlcyI6ZmFsc2V9XSwic3VzcGVjdENvdW50Ijo1LCJjbHVlcyI6W3siaWQiOiJjMzAwOTgiLCJ0eXBlIjoiSU5fQ09MIiwic3ViamVjdElkIjoiczAiLCJzdWJqZWN0TmFtZSI6IkFydHVybyIsImZhY3QiOnsiY29sIjoxfSwiY2F0ZWdvcnkiOiJwb3NpemlvbmUiLCJkaWZmIjoxLCJzY29wZSI6InN1YmplY3QiLCJ0ZXh0IjoiQXJ0dXJvIHNpIHRyb3ZhIG5lbGxhIGNvbG9ubmEgMi4ifSx7ImlkIjoiYzMwMTAyIiwidHlwZSI6IklOX1JPVyIsInN1YmplY3RJZCI6InMxIiwic3ViamVjdE5hbWUiOiJCZWF0cmljZSIsImZhY3QiOnsicm93IjoyfSwiY2F0ZWdvcnkiOiJwb3NpemlvbmUiLCJkaWZmIjoxLCJzY29wZSI6InN1YmplY3QiLCJ0ZXh0IjoiQmVhdHJpY2Ugc2kgdHJvdmEgbmVsbGEgcmlnYSAzLiJ9LHsiaWQiOiJjMzAxMDUiLCJ0eXBlIjoiSU5fQVJFQSIsInN1YmplY3RJZCI6InMyIiwic3ViamVjdE5hbWUiOiJDaGlhcmEiLCJmYWN0Ijp7ImFyZWFJZCI6NH0sImNhdGVnb3J5IjoiYXJlYSIsImRpZmYiOjEsInNjb3BlIjoic3ViamVjdCIsInRleHQiOiJDaGlhcmEgc2kgdHJvdmEgaW4gU3RhbnphIDMxNS4ifSx7ImlkIjoiYzMwMTEyIiwidHlwZSI6Ik9OX09CSkVDVCIsInN1YmplY3RJZCI6InMzIiwic3ViamVjdE5hbWUiOiJEaWVnbyIsImZhY3QiOnsib2JqZWN0S2luZCI6ImxldHRvIn0sImNhdGVnb3J5Ijoib2dnZXR0byIsImRpZmYiOjEsInNjb3BlIjoic3ViamVjdCIsInRleHQiOiJEaWVnbyBzaSB0cm92YSBzdSB1biBMZXR0by4ifSx7ImlkIjoiYzMwMTE4IiwidHlwZSI6IkJFU0lERV9PQkpFQ1QiLCJzdWJqZWN0SWQiOiJzNCIsInN1YmplY3ROYW1lIjoiRWxpbyIsImZhY3QiOnsib2JqZWN0S2luZCI6InNlZGlhIn0sImNhdGVnb3J5Ijoib2dnZXR0byIsImRpZmYiOjEsInNjb3BlIjoic3ViamVjdCIsInRleHQiOiJFbGlvIHNpIHRyb3ZhIGFjY2FudG8gYSB1bmEgU2VkaWEuIn0seyJpZCI6ImMzMDEwMSIsInR5cGUiOiJJTl9BUkVBIiwic3ViamVjdElkIjoiczEiLCJzdWJqZWN0TmFtZSI6IkJlYXRyaWNlIiwiZmFjdCI6eyJhcmVhSWQiOjF9LCJjYXRlZ29yeSI6ImFyZWEiLCJkaWZmIjoxLCJzY29wZSI6InN1YmplY3QiLCJ0ZXh0IjoiQmVhdHJpY2Ugc2kgdHJvdmEgaW4gQ29ycmlkb2lvLiJ9XSwidGhlbWUiOm51bGwsIm5hcnJhdGlvbiI6bnVsbCwibmFycmF0ZWQiOmZhbHNlLCJhaVNvbHV0aW9uIjpbIlBhc3NvIDE6IEV0dG9yZSBzaSB0cm92YSBuZWxsYSByaWdhIHBpw7kgaW4gYmFzc28sIHF1aW5kaSBkZXZlIGVzc2VyZSBpbiByaWdhIDYuIERldmUgaW5vbHRyZSB0cm92YXJzaSBhY2NhbnRvIGEgdW5hIFBhbmNoaW5hLiBMZSBQYW5jaGluZSBzb25vIGluICgxLDIpLCAoNCw0KSBlICg1LDIpLCBtYSBsJ3VuaWNhIGNlbGxhIGRlbGxhIHJpZ2EgNiBhZGlhY2VudGUgYSB1bmEgUGFuY2hpbmEsIG5lbGxhIHN0ZXNzYSBzdGFuemEgZSBzZW56YSB1biBtdXJvIGRpIG1lenpvLCDDqCAoNiwyKS4gRXR0b3JlIMOoIHF1aW5kaSBpbiAoNiwyKS4iLCJQYXNzbyAyOiBCaWFnaW8gaGEgZHVlIGluZGl6aSBkaXJldHRpOiBzaSB0cm92YSBuZWxsYSByaWdhIDIgZSBuZWxsYSBjb2xvbm5hIDQuIExhIHN1YSBwb3NpemlvbmUgw6ggcXVpbmRpIGltbWVkaWF0YW1lbnRlICgyLDQpLiIsIlBhc3NvIDM6IEFydHVybyBkZXZlIHRyb3ZhcnNpIG5lbGxhIGNvbG9ubmEgMy4gTGUgY2VsbGUgKDIsMyksICgzLDMpIGUgKDQsMykgc29ubyBvY2N1cGF0ZSBkYSBvc3RhY29saSwgbWVudHJlIGxhIHJpZ2EgNiDDqCBnacOgIHV0aWxpenphdGEgZGEgRXR0b3JlLiBSZXN0YW5vIHF1aW5kaSBzb2x0YW50byAoMSwzKSBlICg1LDMpIGNvbWUgcG9zc2liaWxpIHBvc2l6aW9uaSBkaSBBcnR1cm8uIiwiUGFzc28gNDogRGVsaWEgZGV2ZSBlc3NlcmUgYWNjYW50byBhIHVuYSBQYW5jaGluYS4gQ29uc2lkZXJhbmRvIHNvbGFtZW50ZSBsJ2FkaWFjZW56YSBvcnRvZ29uYWxlIG5lbGxhIHN0ZXNzYSBzdGFuemEgZSBzZW56YSBtdXJpLCBsZSBjZWxsZSBwb3NzaWJpbGkgc29ubyAoMSwxKSwgKDEsMyksICgzLDQpLCAoNCw1KSwgKDUsMykgZSAoNiwyKS4gKDYsMikgw6ggZ2nDoCBvY2N1cGF0YSBkYSBFdHRvcmU7ICgzLDQpIMOoIG5lbGxhIGNvbG9ubmEgNCBnacOgIG9jY3VwYXRhIGRhIEJpYWdpby4gSW5vbHRyZSBBcnR1cm8gZGV2ZSBuZWNlc3NhcmlhbWVudGUgdXRpbGl6emFyZSBsYSBjb2xvbm5hIDMsIHF1aW5kaSBEZWxpYSBub24gcHXDsiBvY2N1cGFyZSBuw6kgKDEsMykgbsOpICg1LDMpLiBEZWxpYSByZXN0YSBkdW5xdWUgbGltaXRhdGEgYSAoMSwxKSBvcHB1cmUgKDQsNSkuIiwiUGFzc28gNTogU3VwcG9uaWFtbyBEZWxpYSBpbiAoMSwxKS4gQXJ0dXJvIG5vbiBwb3RyZWJiZSBhbGxvcmEgc3RhcmUgaW4gcmlnYSAxIGUgc2FyZWJiZSBvYmJsaWdhdG8gaW4gKDUsMykuIExlIHJpZ2hlIDEsIDIsIDUgZSA2IHNhcmViYmVybyBvY2N1cGF0ZSByaXNwZXR0aXZhbWVudGUgZGEgRGVsaWEsIEJpYWdpbywgQXJ0dXJvIGVkIEV0dG9yZS4gQ2luemlhLCBjaGUgZGV2ZSBlc3NlcmUgbmVpIEdpYXJkaW5pLCBkb3ZyZWJiZSBxdWluZGkgdXRpbGl6emFyZSB1bmEgZGVsbGUgcmlnaGUgYW5jb3JhIGRpc3BvbmliaWxpLiBJbiByaWdhIDMgbCd1bmljYSBjZWxsYSBkZWkgR2lhcmRpbmkgdXRpbGl6emFiaWxlIMOoICgzLDEpLCBtYSBsYSBjb2xvbm5hIDEgc2FyZWJiZSBnacOgIG9jY3VwYXRhIGRhIERlbGlhLiBMJ2lwb3Rlc2kgw6ggaW1wb3NzaWJpbGUuIERlbGlhIGRldmUgcXVpbmRpIGVzc2VyZSBpbiAoNCw1KS4iLCJQYXNzbyA2OiBSZXN0YW5vIHBlciBBcnR1cm8gKDEsMykgZSAoNSwzKS4gU3VwcG9uaWFtbyBBcnR1cm8gaW4gKDUsMykuIENvbiBCaWFnaW8gaW4gcmlnYSAyLCBEZWxpYSBpbiByaWdhIDQgZWQgRXR0b3JlIGluIHJpZ2EgNiwgQ2luemlhIGRldmUgb2NjdXBhcmUgdW5hIGRlbGxlIHJpZ2hlIDEgbyAzIHBlcmNow6kgZGV2ZSBzdGFyZSBuZWkgR2lhcmRpbmkuIExlIGNvbG9ubmUgZ2nDoCB1dGlsaXp6YXRlIHNvbm8gMiwgMywgNCBlIDUsIHF1aW5kaSBhIENpbnppYSBlIGFsbGEgdml0dGltYSByaW1hbmdvbm8gc29sdGFudG8gbGUgY29sb25uZSAxIGUgNi4gU2UgQ2luemlhIGZvc3NlIGluICgxLDEpLCBhbGxhIHZpdHRpbWEgcmltYXJyZWJiZSAoMyw2KSwgY2hlIGNvbnRpZW5lIHVuIENlc3B1Z2xpbyBlZCDDqCBxdWluZGkgaW5hY2Nlc3NpYmlsZS4gU2UgQ2luemlhIGZvc3NlIGluICgzLDEpLCBhbGxhIHZpdHRpbWEgcmltYXJyZWJiZSAoMSw2KSwgY2hlIGNvbnRpZW5lIHVuJ0FpdW9sYSBlZCDDqCBhbmNoJ2Vzc2EgaW5hY2Nlc3NpYmlsZS4gQXJ0dXJvIG5vbiBwdcOyIHF1aW5kaSBlc3NlcmUgaW4gKDUsMykuIiwiUGFzc28gNzogQXJ0dXJvIMOoIG5lY2Vzc2FyaWFtZW50ZSBpbiAoMSwzKS4gTGUgcmlnaGUgb2NjdXBhdGUgc29ubyBvcmEgMSBwZXIgQXJ0dXJvLCAyIHBlciBCaWFnaW8sIDQgcGVyIERlbGlhIGUgNiBwZXIgRXR0b3JlLiBDaW56aWEgZSBaYXJhIGRldm9ubyBxdWluZGkgb2NjdXBhcmUgbGUgcmlnaGUgMyBlIDUuIENpbnppYSBkZXZlIHRyb3ZhcnNpIG5laSBHaWFyZGluaTogaW4gcmlnYSA1IG5vbiBlc2lzdG9ubyBjZWxsZSBkZWkgR2lhcmRpbmksIG1lbnRyZSBpbiByaWdhIDMgbCd1bmljYSBjZWxsYSB1dGlsaXp6YWJpbGUgZGVpIEdpYXJkaW5pIMOoICgzLDEpLiBDaW56aWEgw6ggcXVpbmRpIGluICgzLDEpLiIsIlBhc3NvIDg6IFBlciBsYSBSZWdvbGEgQXVyZWEgcmltYW5lIGFsbGEgdml0dGltYSBaYXJhIGwndW5pY2EgcmlnYSBub24gdXRpbGl6emF0YSwgbGEgcmlnYSA1LCBlIGwndW5pY2EgY29sb25uYSBub24gdXRpbGl6emF0YSwgbGEgY29sb25uYSA2LiBaYXJhIHNpIHRyb3ZhIHF1aW5kaSBpbiAoNSw2KSwgY2hlIMOoIHVuYSBjZWxsYSBsaWJlcmEgZGVsbGEgU3RyYWRhLiIsIlBhc3NvIDk6IFphcmEgw6ggbmVsbGEgU3RyYWRhLiBUcmEgaSBjaW5xdWUgc29zcGV0dGksIEFydHVybywgQmlhZ2lvIGUgQ2luemlhIHNvbm8gbmVpIEdpYXJkaW5pLCBEZWxpYSDDqCBuZWxsYSBGb250YW5hIGVkIEV0dG9yZSDDqCBuZWxsYSBTdHJhZGEuIEV0dG9yZSDDqCBxdWluZGkgbCd1bmljbyBzb3NwZXR0byBuZWxsYSBzdGVzc2Egc3RhbnphIGRlbGxhIHZpdHRpbWEgZSwgc2Vjb25kbyBsYSByZWdvbGEgZGVsbCdlbmlnbWEsIMOoIGwnYXNzYXNzaW5vLiJdLCJhaVZhbGlkYXRpb25Nc2ciOiLinIUgTCdBSSBoYSByaXNvbHRvIGNvcnJldHRhbWVudGUgbGEgbWFwcGEhIExlIHBvc2l6aW9uaSBkZWRvdHRlIGNvbWJhY2lhbm8gcGVyZmV0dGFtYW50ZS4iLCJhaURpZmZpY3VsdHkiOiJNZWRpdW0iLCJhaUh1bWFuRXZhbHVhdGlvbiI6IlB1enpsZSBjb21wYXR0byBtYSBiZW4gY29zdHJ1aXRvOiBpIHByaW1pIGR1ZSBwaWF6emFtZW50aSBzb25vIGltbWVkaWF0aSwgbWVudHJlIGxhIHBhcnRlIGNlbnRyYWxlIHJpY2hpZWRlIGRpIGNvbWJpbmFyZSBsYSBSZWdvbGEgQXVyZWEgY29uIGxhIGdlb21ldHJpYSBkZWxsZSBzdGFuemUsIGkgbXVyaSBlIGxlIGNlbGxlIGJsb2NjYXRlLiBJbCBwYXNzYWdnaW8gcGnDuSBpbnRlcmVzc2FudGUgw6ggRGVsaWE6IGwnaW5kaXppbyBkZWxsYSBQYW5jaGluYSBnZW5lcmEgaW5pemlhbG1lbnRlIHBpw7kgcG9zc2liaWxpdMOgLCBtYSBtb2x0ZSB2ZW5nb25vIGVsaW1pbmF0ZSBkYWxsZSBjb2xvbm5lIGdpw6AgaW1wZWduYXRlIG8gZGFsIGZhdHRvIGNoZSBBcnR1cm8gZGV2ZSBuZWNlc3NhcmlhbWVudGUgb2NjdXBhcmUgbGEgY29sb25uYSAzLiBEYSBsw6wgdW5hIGJyZXZlIHByb3ZhIHBlciBhc3N1cmRvIGVsaW1pbmEgKDEsMSkuIEFuY2hlIEFydHVybyByaWNoaWVkZSBwb2kgdW4gcGljY29sbyByYWdpb25hbWVudG8gcGVyIGVzY2x1c2lvbmU6IGwnYWx0ZXJuYXRpdmEgaW4gcmlnYSA1IGxhc2NlcmViYmUgYWxsYSB2aXR0aW1hIHVuYSBjZWxsYSBibG9jY2F0YSBpbmRpcGVuZGVudGVtZW50ZSBkYWxsYSBzaXN0ZW1hemlvbmUgZGkgQ2luemlhLiBMYSBjb25jbHVzaW9uZSBzdSBDaW56aWEgZSBaYXJhIGRpdmVudGEgcXVpbmRpIHB1bGl0YSBlIHNvZGRpc2ZhY2VudGUuIEwnaWRlbnRpZmljYXppb25lIGZpbmFsZSBkaSBFdHRvcmUgY29tZSBhc3Nhc3Npbm8gYWdnaXVuZ2UgdW4gdWx0aW1vIGNvbnRyb2xsbyBzaWduaWZpY2F0aXZvIHBlcmNow6kgw6ggbCd1bmljbyBzb3NwZXR0byBuZWxsYSBTdHJhZGEgaW5zaWVtZSBhbGxhIHZpdHRpbWEuIE5lbCBjb21wbGVzc28gw6ggdW4gYnVvbiBNZWRpdW06IG5lc3N1bm8gc3RlcCDDqCBlY2Nlc3NpdmFtZW50ZSBjZXJ2ZWxsb3RpY28sIG1hIG5vbiDDqCByaXNvbHZpYmlsZSBzZW1wbGljZW1lbnRlIGxlZ2dlbmRvIGdsaSBpbmRpemkgdW5vIGRvcG8gbCdhbHRybzsgYmlzb2duYSByZWFsbWVudGUgaW5jcm9jaWFybGkgY29uIG1hcHBhLCBvc3RhY29saSBlIHVuaWNpdMOgIGRpIHJpZ2hlIGUgY29sb25uZS4ifQ== -->
